# Generated by Django 5.1 on 2024-11-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigproject', '0004_course_intro_mindfulness_lesson_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_mindfulness_lesson_1_practice',
            field=models.BooleanField(default=False),
        ),
    ]
